name: mattermost-zt-nodejs-webhook
on:
  create:
  delete:
  issues:
  issue_comment:
  pull_request_review:
  pull_request_review_comment:
  pull_request:
  push:
  fork:
  release:

jobs:
  mattermost-zt-nodejs-webhook:
    continue-on-error: true
    runs-on: ubuntu-24.04
    name: POST Webhook with NodeJS
    if: github.repository_owner == 'hanzozt' && github.actor != 'dependabot[bot]'
    env:
      ZITI_LOG: 99
      ZITI_NODEJS_LOG: 99
    steps:
      - uses: hanzozt/zt-webhook-action@main
        with:
          zt-id: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
          webhook-url: ${{ secrets.ZITI_MATTERMOST_WEBHOOK_URL }}
          webhook-secret: ${{ secrets.ZITI_MATTERMOSTI_WEBHOOK_SECRET }}

